apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: echo
spec:
  environments:
    - name: development
      build:
        from: master
    - name: prod
  components:
    - name: test
      image: privaterepodeleteme.azurecr.io/nginx:latest
      publicPort: http
      ports:
       - name: http
         port: 80
      environmentConfig:
        - environment: development
          resources:
            requests:
              memory: "54Mi"
              cpu: "10m"
            limits:
              memory: "54Mi"
          replicas: 1
    - name: www
      src: ./www
      publicPort: http
      ports:
       - name: http
         port: 3000
      environmentConfig:
        - environment: development
          monitoring: false
          resources:
            requests:
              memory: "54Mi"
              cpu: "10m"
            limits:
              memory: "54Mi"
          replicas: 1
    - name: echo
      src: ./echo
      ports:
       - name: http
         port: 3001
      environmentConfig:
        - environment: development
          monitoring: true
          variables:
            PORT: 3001
            NODE_ENV: production
          resources:
            requests:
              memory: "54Mi"
              cpu: "50m"
            limits:
              memory: "54Mi"
          replicas: 2
  dnsAppAlias:
    environment: development
    component: www
  privateImageHubs:
    privaterepodeleteme.azurecr.io:
      username: 814607e6-3d71-44a7-8476-50e8b281abbc
      email: radix@statoilsrm.onmicrosoft.com
